### ISSUE TITLE
有快速获取设备的办法？user id可以通过获取小程序页面路经获取

### ISSUE THREAD

**Issue by wmxerni** [WankkoRee/PartyHistoryofLearning#1]

**Comment by WankkoRee** [comment]
emm，随便找个数据包的发送都能找到啊，稍后补个图

**Comment by WankkoRee** [comment]
我感觉我命名还是挺规范的，都照着原封不动复制了
![file](https://i.loli.net/2021/04/14/PtgWCONJhjluQdT.png)
