### ISSUE TITLE
大佬可以科普下原理吗

### ISSUE THREAD

**Issue by alc0h0l** [WankkoRee/PartyHistoryofLearning#13]
已经成功运行代码。
对其原理感兴趣。
尝试去理解代码，不懂。
大佬能科普一下怎么实现自动答题的吗？

**Comment by WankkoRee** [comment]
总体上原理为模拟小程序的网络数据包，实现脱离人工。
关于如何确定答案，因为这个小程序返回的数据包中本身就包含了被加密过的正确答案，只需解密即可获得正确答案。
