### ISSUE TITLE
关于UID的获取

### ISSUE THREAD

**Issue by by7741** [WankkoRee/PartyHistoryofLearning#2]
有没有什么方法可以直接获取UID的

**Comment by WankkoRee** [comment]
可以参照我在 #1 发的截图。

**Comment by by7741** [comment]
哪里可以调速度的快慢呢，目前速度在10秒56分左右，可不可以让他速度更快一点呢

**Comment by WankkoRee** [comment]
有两个地方可以调速度。
1. `randSleepTime = 3`
   这个看变量备注就行。
2. `time.sleep(2)`
   这个可大可小，是每轮答题的间隔（相当于真实答题时，页面回退、前进消耗的时间）

还有个不建议更改的阅读消耗时长，改了之后可能会被检测。
`sleeptime.append(len(q['content']) // 10)`
这个是小程序里本身就有的读题时间，也就是选项是灰色的时候。
如果要减少时间的话，可以将`10`改大。
