### ISSUE TITLE
判断出错

### ISSUE THREAD

**Issue by Devil-09** [WankkoRee/PartyHistoryofLearning#3]
assert ret['code'] == 0 and ret['msg'] == '提交完成'
AssertionError

到这一步

**Comment by WankkoRee** [comment]
之前运行正常吗？如果没有运行成功过，请确认两个参数是否填写正确。

如果是突然无法使用，那可能是服务器问题或脚本需要更新。

我明天工作时间会进行确认。

**Comment by Devil-09** [comment]
![image](https://user-images.githubusercontent.com/69424762/117579868-86e61a80-b127-11eb-9c43-12fcfaddca62.png)

**Comment by WankkoRee** [comment]
测试未发现功能失效。请确认`device_info`、`user_id`两个参数是否填写正确。
![image](https://user-images.githubusercontent.com/21287731/117648400-be54d580-b1c0-11eb-8c78-b6789485074f.png)

**Comment by Devil-09** [comment]
> 测试未发现功能失效。请确认`device_info`，`user_id`两个参数是否填写正确。
> ![图像](https://user-images.githubusercontent.com/21287731/117648400-be54d580-b1c0-11eb-8c78-b6789485074f.png)

![image](https://user-images.githubusercontent.com/69424762/117665643-a0de3680-b1d5-11eb-8259-3bb4fa1a7e7b.png)

**Comment by Devil-09** [comment]
是这两个吗

**Comment by WankkoRee** [comment]
是的。

**Comment by Devil-09** [comment]
> 是的。

真的不行，

**Comment by Devil-09** [comment]
> 是的。

![image](https://user-images.githubusercontent.com/69424762/117666904-eb13e780-b1d6-11eb-9794-107bf9d574f8.png)

**Comment by WankkoRee** [comment]
调试模式下看看报错时变量`ret`是什么，应该有服务器返回的消息。

**Comment by Devil-09** [comment]
> 调试模式下看看报错时变量`ret`是什么，应该有服务器返回的消息。

![Uploading image.png…]()

**Comment by Devil-09** [comment]
> 调试模式下看看报错时变量`ret`是什么，应该有服务器返回的消息。

![image](https://user-images.githubusercontent.com/69424762/117668190-48f4ff00-b1d8-11eb-85b0-9d1301e7f74c.png)

**Comment by Devil-09** [comment]
> 调试模式下看看报错时变量`ret`是什么，应该有服务器返回的消息。

![image](https://user-images.githubusercontent.com/69424762/117669704-c705d580-b1d9-11eb-9889-cc78e121c36a.png)

**Comment by WankkoRee** [comment]
我使用你的id测试了一次，排除了是账号的问题。

你对脚本有其他任何更改吗？

![image](https://user-images.githubusercontent.com/21287731/117670250-4a272b80-b1da-11eb-909b-4150664b77b6.png)

**Comment by Devil-09** [comment]
> 我使用你的id测试了一次，排除了是账号的问题。
> 
> 你对脚本有其他任何更改吗？
> 
> ![image](https://user-images.githubusercontent.com/21287731/117670250-4a272b80-b1da-11eb-909b-4150664b77b6.png)

没有更改，我还特意的去重新下一编，还是一样

**Comment by Devil-09** [comment]
> > 我使用你的id测试了一次，排除了是账号的问题。
> > 你对脚本有其他任何更改吗？
> > ![image](https://user-images.githubusercontent.com/21287731/117670250-4a272b80-b1da-11eb-909b-4150664b77b6.png)
> 
> 没有更改，我还特意的去重新下一编，还是一样

要不你发这个文本我试试

**Comment by WankkoRee** [comment]
刚才看你的截图发现我代码上传的数据有问题，但是这个bug官方并没有做判断，不确定是不是你现在遇到的问题，你可以更新一下修复的 aab079f 试试。

**Comment by Devil-09** [comment]
> 刚才看你的截图发现我代码上传的数据有问题，但是这个bug官方并没有做判断，不确定是不是你现在遇到的问题，你可以更新一下修复的 [aab079f](https://github.com/WankkoRee/PartyHistoryofLearning/commit/aab079fa4b94704b3749f9629e859622e76398a7) 试试。

![image](https://user-images.githubusercontent.com/69424762/117673643-8a3bdd80-b1dd-11eb-8653-7431be2d50c8.png)
还是一样

**Comment by WankkoRee** [comment]
抱歉，此问题可能需要我进行远程协助。
如果可以的话，你可以[加我的QQ](http://wpa.qq.com/msgrd?v=3&uin=1984933075&site=qq&menu=yes)。

**Comment by WankkoRee** [comment]
结论：系统时间误差过大，需与北京时间校准。
