### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by aingjk** [WankkoRee/PartyHistoryofLearning#7]
大大，能否写一个云函数（Serverless Cloud Function，SCF）版本，放在服务器上可以自动触发运行，以及控制一下回答的胜率，胜率100%，太高了~

**Comment by WankkoRee** [comment]
我没有接触过云函数，可能需要你自己进行修改。
胜率控制将在下次commit中加上。

**Comment by WankkoRee** [comment]
5985dd4
