### ISSUE TITLE
大佬 有贵州一起学党史的python脚本？

### ISSUE THREAD

**Issue by wmxerni** [WankkoRee/PartyHistoryofLearning#8]

**Comment by WankkoRee** [comment]
这玩意还分地区的？

**Comment by wmxerni** [comment]
贵州又出了一个 网页版的 在贵州教育发布那个公众号里

**Comment by WankkoRee** [comment]
贵州这个是完全另一个项目了，需要重写。
但是我没有相关账号，无法进行脚本编写。

**Comment by wmxerni** [comment]
可以直接注册的 不需要验证 随便填一个学校

**Comment by wmxerni** [comment]
我注册的时候 没看到验证学号这些

**Comment by WankkoRee** [comment]
抱歉，由于我并没有这个版本的需求，我不会去制作这个版本。
网页版本的逆向相对来说比小程序更加简单，你可以试着自己编写脚本。
